import React from 'react'
import Head from 'next/head'
import NextIcon from './NextIcon'
import TMDBIcon from './TMDBIcon'
import { Lato } from '@next/font/google'

const lato = Lato({
  weight: ['100', '300', '400', '700', '900'],
  display: 'swap',
  style: ['italic', 'normal'],
})

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div className={`flex min-h-screen flex-col pb-10 ${lato.className}`}>
      <Head>
        <title>T3 TMDB</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center justify-center">
        <div className="flex items-center gap-x-10">
          <NextIcon />
          <TMDBIcon className="w-20" />
        </div>
      </div>
      {children}
    </div>
  )
}
