import React from 'react'
import Head from 'next/head'

import { Lato } from '@next/font/google'
import Footer from './Footer'
import Header from './Header'
import Navigation from './Navigation'

const lato = Lato({
  weight: ['100', '300', '400', '700', '900'],
  display: 'swap',
  style: ['italic', 'normal'],
})

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div className={`flex min-h-screen flex-col  pb-10 ${lato.className}`}>
      <Head>
        <title>T3 TMDB</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Navigation />
      {children}
      <Footer />
    </div>
  )
}
